### ISSUE TITLE
sentis

### ISSUE THREAD

**Issue by qq1342753906** [pnltoen/Barracuda_AdaIN#2]
Can sentis be run in multiple threads? Even if there is no frame parsing model in the update, it will not affect the running frame rate of the project?

**Comment by pnltoen** [comment]
Reading a reply from [alexandreribard_unity](https://discussions.unity.com/u/alexandreribard_unity) on the [post](https://discussions.unity.com/t/how-to-use-multi-threading/307154) seems benefical for you
